Solution for Exercise 02-04 from Chapter 02 in Baby Rudin
ceciliachan1979/math pull request #47
Opened 2024-02-16 06:54 UTC by Kelvinyu1117

This pull request provides the solution for Exercise 02-04, Chapter 02, from the third edition of Principles of Mathematical Analysis by Walter Rudin.

2024-02-16 11:15 UTC, E7-87-83 requested changes
Ex03和Ex04 ok.

2024-02-16 11:15 UTC, E7-87-83 commented on Books/BabyRudin/Chapter02/ex02.kelvin.tex
> +and $\bigcup_{N \in \mathbb{N+}} A_N$ is finite due to the union of finite sets is finite, which means the set of all complex polynomials with integer coefficient is countable.
一、
\bigcup_{N \in \mathbb{N+}} A_N
係咪應該係 \bigcup_{N \in \mathbb{Z^+}} A_N
二、
A finite union of finite sets is finite.

A countable union of finite sets is at most countable.

2024-02-16 11:15 UTC, E7-87-83 commented on Books/BabyRudin/Chapter02/ex02.kelvin.tex
> +$\forall{N} \in \mathbb{Z^+}, B_N = \{z \in \mathbb{C}\mid A_N(z) = 0\}$
\forall{N} \in \mathbb{Z^+}, B_N = \{z \in \mathbb{C}\mid f(z) = 0 for some f \in A_N\}

2024-02-16 13:33 UTC, ceciliachan1979 commented on Books/BabyRudin/Chapter02/ex03.kelvin.tex
> +However, as $\mathbb{R}$ is uncountable and $A$ is countable from Exercise 2, which means $|\mathbb{R}| > |A|$ and $\mathbb{R} \setminus A \neq \phi$, which leads to contradiction.
呢個 notation 好似唔係好得，$`|\mathbb{R}| > |A|`$

2024-02-16 15:54 UTC, Kelvinyu1117 commented on Books/BabyRudin/Chapter02/ex02.kelvin.tex
> +$\forall{N} \in \mathbb{Z^+}, B_N = \{z \in \mathbb{C}\mid A_N(z) = 0\}$
fixed.

2024-02-20 14:12 UTC, Kelvinyu1117 commented on Books/BabyRudin/Chapter02/ex02.kelvin.tex
> +and $\bigcup_{N \in \mathbb{N+}} A_N$ is finite due to the union of finite sets is finite, which means the set of all complex polynomials with integer coefficient is countable.
Fixed. Can you have a look again?

2024-02-20 16:19 UTC, ceciliachan1979 approved these changes

2024-02-20 16:19 UTC, merged