Practice problems
ceciliachan1979/math pull request #90
Opened 2024-07-31 14:19 UTC by ceciliachan1979

2024-08-01 21:39 UTC, AoiYamada commented on Misc/Practice/Practice.tex
> +      p(x) &= ax^5 + (-3a + b)x^4 + (3a - 3b + c)x^3 + (-a + 3b - 3c)x^2 + (-bx + 3c)x + (-c - 1)
```suggestion
           &= ax^5 + (-3a + b)x^4 + (3a - 3b + c)x^3 + (-a + 3b - 3c)x^2 + (-b + 3c)x - c        \\
      p(x) &= ax^5 + (-3a + b)x^4 + (3a - 3b + c)x^3 + (-a + 3b - 3c)x^2 + (-b + 3c)x + (-c - 1)
```
typo?

2024-08-01 21:39 UTC, AoiYamada commented on Misc/Practice/Practice.tex
> +      p(x) &= dx^5 + (3d + e)x^4 + (3d + 3e + f)x^3 + (d + 3e + 3f)x^2 + (ex + 3f)x + (f + 1) \\
```suggestion
           &= dx^5 + (3d + e)x^4 + (3d + 3e + f)x^3 + (d + 3e + 3f)x^2 + (e + 3f)x + f       \\
      p(x) &= dx^5 + (3d + e)x^4 + (3d + 3e + f)x^3 + (d + 3e + 3f)x^2 + (e + 3f)x + (f + 1) \\
```

2024-08-02 10:09 UTC, Andy-Berkshire requested changes
Line 61, replace 5x^3/8 with 10x^3/8

2024-08-02 10:20 UTC, Andy-Berkshire commented on Misc/Practice/Practice.tex
> +  p_{k+1}(k+1) &= p_k(x + 1) + Cx(x-1)\cdots(x - k) \\
2^{k+1} = p_{k+1}(k+1) &= \left. p_k(x) + Cx(x-1)\cdots(x - k) \right|_{x=k+1}

2024-08-02 10:21 UTC, Andy-Berkshire commented on Misc/Practice/Practice.tex
> +               &= 2^{k + 1} &\text{As required}
delete this line

2024-08-02 10:26 UTC, Andy-Berkshire commented on Misc/Practice/Practice.tex
> +  p(x) &= -\frac{3x^5}{8} + \frac{5x^3}{8} - \frac{15x}{8}
replace 5x^3/8 with 10x^3/8

2024-08-02 19:22 UTC, AoiYamada commented on Misc/Practice/Practice.tex
> +This is a rather brute force solution, I guess better solution exists.
Looks like Chinese Remainder Theorem problem
here is the CRT approach:

Given
p - 1 = 0 (mod (x + 1)^3)

get
p = 1 + g(x)(x + 1)^3

Given
p + 1 = 0 (mod (x - 1)^3)
and substitute

get
1 + g(x)(x + 1)^3 + 1 = (mod (x - 1)^3)
g(x)(x + 1)^3 = -2 (mod (x - 1)^3)
g(x)(x + 1)^3 + h(x)(x - 1)^3 = -2

(x + 1)^3 & (x - 1)^3 are relatively prime

by WolframAlpha solve (use extended Euclidean algorithm, I don't know what's going on)
PolynomialExtendedGCD[ (x + 1)^3, (x-1)^3 ]

get
g(x) = -2(96x^2 - 288x + 256)/512
h(x) = -2(-96x^2 - 288x - 256)/512

by substitution
p
= 1 + g(x)(x + 1)^3
= 1 - 2(96x^2 - 288x + 256)(x + 1)^3/512
= (-3x^5 + 10x^3 - 15x)/8 

verified by symbolab
https://www.symbolab.com/solver/polynomial-long-division-calculator/long%20division%20%5Cfrac%7B%5Cfrac%7B-3x%5E%7B5%7D%2B10x%5E%7B3%7D-15x%7D%7B8%7D-1%7D%7B%5Cleft(x%2B1%5Cright)%5E%7B3%7D%7D?or=input
https://www.symbolab.com/solver/polynomial-long-division-calculator/long%20division%20%5Cfrac%7B%5Cfrac%7B-3x%5E%7B5%7D%2B10x%5E%7B3%7D-15x%7D%7B8%7D%2B1%7D%7B%5Cleft(x-1%5Cright)%5E%7B3%7D%7D?or=input

Yet, I think it is a kind of brute force too LOL

2024-08-03 13:02 UTC, ceciliachan1979 commented on Misc/Practice/Practice.tex
> +This is a rather brute force solution, I guess better solution exists.
```
Euclidean algorithm:

x^3 + 3x^2 + 3x + 1 = 1           (x^3 - 3x^2 + 3x - 1) + 6x^2 + 2
x^3 - 3x^2 + 3x - 1 = (x/6 - 1/2) (6x^2 + 2)            + 8x/3
6x^2 + 2            = (9x/4)      8x/3                  + 2

Extended:

From the last line, we have:
   2 = (6x^2 + 2) - (9x/4)(8x/3)

Moving up, trying to introduce (x^3 - 3x^2 + 3x - 1) and eliminate 8x/3
   2 = (6x^2 + 2) - (9x/4)((x^3 - 3x^2 + 3x - 1) - (x/6 - 1/2) (6x^2 + 2))
     = (6x^2 + 2) - (9x/4)(x^3 - 3x^2 + 3x - 1) + (9x/4)(x/6 - 1/2) (6x^2 + 2)
     = (3x^2/8 - 9x/8 + 1) (6x^2 + 2) - (9x/4)(x^3 - 3x^2 + 3x - 1) 

Moving up, trying to introduce (x^3 + 3x^2 + 3x + 1 = 1) and eliminate 6x^2 + 2
   2 = (3x^2/8 - 9x/8 + 1) ((x^3 + 3x^2 + 3x + 1) - (x^3 - 3x^2 + 3x - 1)) - (9x/4)(x^3 - 3x^2 + 3x - 1) 
     = (3x^2/8 - 9x/8 + 1) ((x^3 + 3x^2 + 3x + 1) - (x^3 - 3x^2 + 3x - 1)) - (9x/4)(x^3 - 3x^2 + 3x - 1) 
     = (3x^2/8 - 9x/8 + 1) (x^3 + 3x^2 + 3x + 1) - (3x^2/8 + 9x/8 + 1) (x^3 - 3x^2 + 3x - 1)
```

2024-08-03 23:13 UTC, merged